### ISSUE TITLE
very outdated data is displayed

### ISSUE THREAD

**Issue by momolinus** [sozialhelden/wheelmap-frontend#361] opened 2022-05-20 13:10 UTC
as you can see here, places are shown which do not exist in the OpenStreetMap for a long time anymore:

https://wheelmap.org/nodes/eF6doZpvBJtfu3Ret
https://wheelmap.org/nodes/277270271

**Comment by momolinus** [comment] 2022-05-20 13:14
as you can see here:
https://wheelmap.org/nodes/68XAv6Bviv4K8vduy
old and new data are shown

**Comment by opyh** [comment] 2022-12-05 13:29
The PR shown above fixes this problem. It will take a while until the code is in a deployable state, but we're on it. There will be a public beta. Until then, you can check out our new backend debugger to see the current state of the data for the place you've mentioned above: https://sozialhelden.github.io/planet-accessibility-explorer/#/planet-accessibility-explorer/buildings/107736275?lon=13.341415741353844&lat=52.46914184635515&zoom=19.045072332637723

**Comment by Elefant-aus-Wuppertal** [comment] 2023-05-14 18:33
I just find it difficult that the map data is still outdated at the moment, but then live editing is allowed (of objects that de facto no longer exist, for a long time, example: https://www.openstreetmap.org/node/1890415985/history )

**Comment by opyh** [comment] 2023-06-02 17:50
@Elefant-aus-Wuppertal You are right, this is bad.

We're getting closer to a fix though. Please 🐻 with us.

The current state is:

- Our new OSM backend syncs data reliably (from OSM to our DB) within 1-2h.
- The code to store new (small, atomic) OSM changesets is written and tested, but not integrated into the frontend yet.
- Since today, we have a dev/testing deployment of the new frontend at https://feature-attach-osm-api.wheelmap.tech/

What you find there is not complete yet, expect bugs. Known issues:

- Editing accessibility doesn't work yet as the code is not integrated yet.
- Loading places is slow as the tile data is not CDN-cached yet.
- Filtering places by category is not wired yet.
- Older photos from the legacy backend are not migrated to the new backend yet.
- Many places don't have correct icons yet / are not correctly categorized, as the new backend delivers new place types.

**Comment by Elefant-aus-Wuppertal** [comment] 2023-06-03 13:37
Thank you for the update. I am confident that this will work. Sure, no problem, it will take some time. But to see that people are working on it is very good.

**Comment by Elefant-aus-Wuppertal** [comment] 2023-06-03 13:48
By the way, I don't know exactly if we'd have to take new objects like **amenity=waste_basket** or **amenity=bench** into account (I saw them in the new frontend, even if they are not categorized correctly yet), because I wouldn't know how to indicate any wheelchair accessibility for these objects.

**Comment by opyh** [comment] 2023-06-12 11:03
Thanks for the report and for taking the time to look at the deployment! This is a known issue :) We will hide these (and some other types of) objects before releasing this in production.

**Comment by opyh** [comment] 2023-07-06 13:50
We're slowly approaching a [state that is ready for a production deployment](https://feature-attach-osm-api.wheelmap.tech/).

- [x] Editing wheelchair accessibility works with small changesets
- [x] Loading places is not slow anymore (CDN)
- [x] Filtering places by category is wired
- [x] Older photos from the legacy backend are migrated to the new backend
- [ ] Some places don't have correct icons yet / are not correctly categorized
- [ ] Some transit-related PoI types are still missing (ex. platforms)
- [ ] URL format is not yet backwards-compatible
- [ ] Clicking on PoIs can cause JS crashes in a few cases

The last missing points shouldn't be complicated to fix. Our team is really looking forward to this deployment :)

**Comment by map-per** [comment] 2023-09-13 14:19
Overall this looks good to me. But some finetunig is still needed. 
While testing I found these bugs:

- UX: If you change a place from e.g. wheelchair=yes to no this change is not persistent on the user side, as the icon and colour changes back shortly afterwards. After a reload of the page everything is displayed correctly. (Browser: Firefox, Windows) (The edit was correctly forwarded to the OSM database)

- This office=it is displayed with a supermarket icon (https://beta.wheelmap.org/node/7806703230)
- wheelchair=* is asked for an (de)"Unbekannter Ort" (en: unknown place) (The quest should require a name or a category) (https://beta.wheelmap.org/node/9722827660) 
- adding wheelchair=* to a public_transport=stop_area relation doesn't make sense (https://www.openstreetmap.org/changeset/141212302)
- wheelchair=* is asked for guidepost (https://beta.wheelmap.org/node/7826902585)
- wheelchair=* is asked for an artwork (https://beta.wheelmap.org/node/8475611454)
- Not sure if wheelchair=* for individual parking_spaces is right (https://beta.wheelmap.org/way/994977825)
- UX: Better explain how an amenity=charging_station need to be designed to be wheelchair accessible

**Comment by opyh** [comment] 2023-09-28 08:47
Thanks for your report!

> UX: If you change a place from e.g. wheelchair=yes to no this change is not persistent on the user side, as the icon and colour changes back shortly afterwards. After a reload of the page everything is displayed correctly. (Browser: Firefox, Windows) (The edit was correctly forwarded to the OSM database)

Noted, this will be fixed (maybe after the release though, as it is a bug that exists in the live version already)

> This office=it is displayed with a supermarket icon (https://beta.wheelmap.org/node/7806703230)

Makes sense to change the icon :)

> wheelchair=* is asked for an (de)"Unbekannter Ort" (en: unknown place) (The quest should require a name or a category) (https://beta.wheelmap.org/node/9722827660)

Definitely a bug.

> UX: Better explain how an amenity=charging_station need to be designed to be wheelchair accessible

Good point. We will consider this for the roadmap.

Here are some things that I wouldn't change, but I see where your points are coming from and still appreciate the feedback a lot! For special PoIs like parking spaces, charging stations, guide posts etc. it would be really good to have extra information for people who want to tag these features to get better data quality. Still, there are some strong points _for_ the  `wheelchair=*` tag:

> adding wheelchair=* to a public_transport=stop_area relation doesn't make sense (https://www.openstreetmap.org/changeset/141212302)

According to taginfo, there are >1000 taggings like this. `stop_area`s can often be mapped to official datasets in public transport (see GTFS, NeTEx) via their `ref:*` tags, where wheelchair accessibility information exists in public datasets. The info 'the part of a station that is called like X is wheelchair accessible' is knowledge that a local resident mapper or transit agency usually knows as well.

> wheelchair=* is asked for guidepost (https://beta.wheelmap.org/node/7826902585)

Many guideposts are not wheelchair accessible (mounted too high + small font size) and it's helpful for wheelchair users and maintainers to mark this, as the posts are often a vital part of navigation around places like tourism viewpoints and transit stations. I know it doesn't make sense to mark _every_ guidepost though :) The problem is that guidepost tags are rarely coming with a more specific `guidepost=*` tag, so the app can't know how important the tag is. A description in the UI like "please only tag guideposts with small font sizes or with a lot of text" would be good though.

> wheelchair=* is asked for an artwork (https://beta.wheelmap.org/node/8475611454)

Why do you think that this is a bug? If a statue with a sign with steps in front, you can't read the sign. It's also good to know in advance which artworks in a museum you can actually access as a wheelchair user. For wheelchair users interested in art, this is helpful information.

> Not sure if wheelchair=* for individual parking_spaces is right (https://beta.wheelmap.org/way/994977825)

23784 places with a `parking_space` tag also have a `wheelchair` tag, that's 4%. Note that there is a difference in actual accessibility for wheelchair users (`wheelchair=*`) and the _designated_ accessibility (`parking_space=disabled`):

![image](https://github.com/sozialhelden/wheelmap-frontend/assets/192912/926faeab-24b9-4bb4-9994-903e89e4f5b2)

[This blog post](https://aoausa.com/ada-parking-space-common-mistakes-what-is-wrong-with-this-picture-by-anthony-c-guichard/) describes more typical mistakes where the tagging makes sense.

**Comment by map-per** [comment] 2023-10-08 09:45
I think, especially as WheelMaps bypasses the requirement to create an OSM account and contacting users in case they make systematik mistakes is therefore not possible, editing should be foolproof (like StreetComplete) for people who don't know anything about OSM.

**Comment by opyh** [comment] 2023-11-29 11:34
Most of the fixes are live now. Feel free to create new single issues if you think something is missing :)

Thanks again for your reports!

**Closed by opyh** 2023-11-29 11:34 UTC
